### PR TITLE
Issue179

### PR DESCRIPTION
**Pull request by juga0**

### CODE REVIEW

**Comment by juga0** [comment]
Fixes #179

**Comment by juga0** [comment]
Tests pass, ready to merge from my side

**Comment by pastly** [comment]
Can you add a `latest.v3bw` symlink? After that I'll merge.

That was easier than I thought it would be!

**Comment by juga0** [comment]
Oh sorry, forgot...

**Comment by juga0** [comment]
and i probably should also lock the dir before writing?

**Comment by pastly** [comment]
> and i probably should also lock the dir before writing?

Yeah. Good catch.

**Comment by juga0** [comment]
I started to change ``test_generate.py`` to don't use ``/dev/stdout`` (so that ``DirectoryLock`` can work), but it was lot of changes/work, so i just added a condition in ``write``

**Comment by juga0** [comment]
Ready to merge

**Comment by pastly** [comment]
`latest.v3bw` is created in the pwd, not the `v3bw_dname`.

If `latest.v3bw` already exists, a traceback is generated instead of removing and recreating it

**Comment by juga0** [comment]
ops, let me fix it

**Comment by juga0** [comment]
Should be ready...

**Pull request merged**
