### PR TITLE
Logging overhaul

### PR DESCRIPTION
**Pull request by pastly**
I don't like that we specify `--log-level debug` in most tests, and I hope we can stop having to do that. I created https://trac.torproject.org/projects/tor/ticket/26644 for that.

Closes GH #186

### CODE REVIEW

**Comment by juga0** [comment]
Oh no, i was afraid this might happen, and that's why i commented in https://github.com/pastly/simple-bw-scanner/pull/222#issuecomment-402415406 and https://github.com/pastly/simple-bw-scanner/issues/209#issuecomment-402505896 that i was working on it, and i was about to push.
We both worked on the same tests, and now rebasing my changes on yours is going to be a pain :/
Give me some days to review this, i don't file right now reworking on what i've last hours.
Maybe for big changes or changes across several files, we should notify somehow and wait for ACK, i should have waited to know you were fine with me working on this.

**Comment by juga0** [comment]
I also said i was working on this on IRC, you're usually there

**Comment by pastly** [comment]
You can cherry pick the commit that touches the test cases, or I can revert the commit on this branch (making tests fail). Or we can resolve and conflicts when they come up. It should be very easy since all I did was change DEBUG to debug. That's what l you wish I didn't do, right?

**Comment by juga0** [comment]
You were right, was easy, merging.

**Pull request merged**
