### PR TITLE
Implement the "MaxAdvertisedBandwidth" hack ...

### PR DESCRIPTION
**Pull request by pastly**
Use a relay's {,Relay}BandwidthRate/MaxAdvertisedBandwidth as an
upper bound on the measurements we make for it.

### CODE REVIEW

**Comment by juga0** [comment]
I didn't work on this yet because i wanted to look at tor code and check what teor commented in #8494, but i haven't done it yet.
This PR looks good to me, but we don't have any way to test it.
Would be easy to create a test for this?.

**Comment by pastly** [comment]
I could make another testnet like simple-ipv4 and simple-ipv6 made up of relays with a variety of MaxAdvertisedBandwidth settings. The test would **not** be run automatically.

**Comment by teor2345** [comment]
> I didn't work on this yet because i wanted to look at tor code and check what teor commented in #8494, but i haven't done it yet.

I didn't see any questions for me in #8494, so I left a comment saying what still needs to be done to close that ticket:
https://trac.torproject.org/projects/tor/ticket/8494#comment:10

**Comment by juga0** [comment]
teor:
>> I didn't work on this yet because i wanted to look at tor code and check what teor commented in #8494, but i haven't done it yet.
> 
> I didn't see any questions for me in #8494, so I left a comment saying what still needs to be done to close that ticket:
> https://trac.torproject.org/projects/tor/ticket/8494#comment:10

Thanks for that comment, i didn't realize we should modify also the spec.

The comment i meant to make is that i'm not sure whether Tor code is
already limiting the measured bandwidth by some parameter, though it
does not look like.
I also thought that maybe we should implement this in the Tor code when
the DirAuths read the bandwidth files, but then we would need to check
whether file coming from sbws and not Torflow.
So yes, it seems that we should implement this in sbws.

**Comment by juga0** [comment]
> I could make another testnet like simple-ipv4 and simple-ipv6 made up of relays with a variety of MaxAdvertisedBandwidth settings. The test would **not** be run automatically.

i have not followed how much differ the previous testnets and the
current integration net.tar.
Would it work to make a similar test to
``integration/lib/test_relaylist.py``?.

**Comment by juga0** [comment]
While the changes here would work, now i'm thinking that it would be better to keep track on which was the real measured bandwidth, it might be useful at some point to debug issues.
It also feels less hacking that doing ``amount = average_bandwidth * duration`` to obtain ``average_bandwidth`` when we divide ``amount`` by ``duration``.
What i would propose it that we add ``average_bandwidth`` to ``ResultSuccess``, and we limit the measured bandwidth only in the moment where it's actually calculated to be written in the file: https://github.com/pastly/simple-bw-scanner/blob/master/sbws/lib/v3bwfile.py#L308
What do you think about this?, let me know if you prefer i would implement this.

**Comment by juga0** [comment]
s/hacking/hacky/

**Comment by pastly** [comment]
> ow i'm thinking that it would be better to keep track on which was the real measured bandwidth, it might be useful at some point to debug issues.

I can make the requested changes.

> i have not followed how much differ the previous testnets and the current integration net.tar.

IIRC net.tar is essentially simple-ipv4.

I think I've realized a way we can test this feature without having to literally run `sbws scanner` and will work on implementing my idea. (Essentially call `measure_relay` with a target relay ... don't know why that wasn't obvious to me)

**Comment by pastly** [comment]
All that I think is left is either fixing or removing the broken unit tests.

**Comment by pastly** [comment]
I'm ready for review again.

**Comment by juga0** [comment]
I can check this on saturday, if it's blocking something else, just merge.
In a really quick look, i see it's about tests, not sure if there's also what commented in https://github.com/pastly/simple-bw-scanner/pull/191#issuecomment-397867631

**Comment by pastly** [comment]
The new commits are essentially


### Tests
- add relay with MaxAdvertisedBandwidth to net.tar
- add relay with RelayBandwidthRate to net.tar
- add integration tests that measure the aforementioned relays
- remove tests for `sbws generate`

### Be less hacky

- change ResultSuccess to store the relay's `average_bandwidth` as it was at measurement time (this required a bump in result version)
- remove the hack you didn't like (because you're right, it was hacky)
- limit bandwidths at `sbws generate` time, not at measurement time

**Comment by juga0** [comment]
> change ResultSuccess to store the relay's average_bandwidth as it was at measurement time (this required a bump in result version)

perfect,  i see the commit https://github.com/pastly/simple-bw-scanner/pull/191/commits/c7eda42e58a3fb328def64355e093440d4bca1af

> remove tests for sbws generate

i guess this is because they were breaking and we wanted to change them anyway?

> add relay with MaxAdvertisedBandwidth to net.tar
> add relay with RelayBandwidthRate to net.tar

not related to this ticket, i don't know if net.tar should be just a dir, so we see the changes, though i know it's big and mostly key files

In any case, LGTM, so i'll merge after your reply (unless you would like to do some other change).

**Comment by pastly** [comment]
Yeah I kind of think that net.tar should maybe be a directory.... Except it's full of key material. Conflicted on that, but it's not worth blocking this ticket to figure it out. 

Please merge! :)

On June 23, 2018 9:44:02 AM EDT, juga0 <notifications@github.com> wrote:
>> change ResultSuccess to store the relay's average_bandwidth as it was
>at measurement time (this required a bump in result version)
>
>perfect,  i see the commit
>https://github.com/pastly/simple-bw-scanner/pull/191/commits/c7eda42e58a3fb328def64355e093440d4bca1af
>
>> remove tests for sbws generate
>
>i guess this is because they were breaking and we wanted to change them
>anyway?
>
>> add relay with MaxAdvertisedBandwidth to net.tar
>> add relay with RelayBandwidthRate to net.tar
>
>not related to this ticket, i don't know if net.tar should be just a
>dir, so we see the changes, though i know it's big and mostly key files
>
>In any case, LGTM, so i'll merge after your reply (unless you would
>like to do some other change).
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pastly/simple-bw-scanner/pull/191#issuecomment-399679454

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
