### PR TITLE
Collect globals and standardize their names

### LINKED ISSUE #116: Gather all global constants, and make their naming consistent
In `sbws/globals.py` we have 

- `G_PKG_DIR` where the G was supposed to stand for global
- and other ALL_CAPS constants

In `sbws/__init__.py` we have

- `version`
- `res_proto_ver`
- `wire_proto_ver`

---

- [ ] pick one file or the other.
- [ ] Pick a naming scheme. `G_FOO` or `FOO` is what I'd prefer.
- [ ] If we change the name or location of `version`, we need to update `setup.py` and `docs/source/conf.py` and (if we've merged @juga0's V3BwHeader PR) `sbws/lib/v3bwfile.py`

### PR DESCRIPTION
**Pull request by pastly**
GH: closes #116

### CODE REVIEW

**Comment by juga0** [comment]
Nit-picking mode on:
This is not very important, but never saw program version in capitals before and i'd try to follow standards whenever we can.
In https://github.com/pastly/simple-bw-scanner/issues/39#issuecomment-378558095 i said:
> Usually program version is in __init__.py or _version.py. I haven't look if PEP has recommendations on it.
You asked in IRC and i replied i don't think you should move things in globals.py to __init__.py
Now checked, PEP about version: https://www.python.org/dev/peps/pep-0396/#id25
PEP about where says how to write constants: https://www.python.org/dev/peps/pep-0008/
I usually see "globals" in settings.py or files like that.
I'd leave constants in capitals in one file other than __init__.py and leave __version__ in it, but up to you.

**Comment by pastly** [comment]
Hey @juga0 

Do things look better and more standardized now? Thanks for teaching me about more PEP/python standards.

**Comment by juga0** [comment]
Now looks great!, thanks for accepting the suggestion.
From my side is ready to merge, i can do it if you prefer.

**Comment by pastly** [comment]
Feel free to merge my PRs in the future. I'll hit the button for this one since I'm here writing this comment.

**Pull request merged**
